# Generated by Django 5.2.6 on 2025-09-27 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nome', 'departamento')},
        ),
        migrations.AlterUniqueTogether(
            name='disciplina',
            unique_together={('nome', 'departamento')},
        ),
        migrations.AddField(
            model_name='departamento',
            name='unidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='app.unidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='unidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='app.unidade'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nome', 'unidade')},
        ),
    ]
