# Generated by Django 5.2.6 on 2025-09-27 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_unidade_alter_curso_nome_alter_departamento_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='app.unidade'),
        ),
    ]
