# Generated by Django 5.2.6 on 2025-09-27 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_pessoa_unidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='creditos',
            new_name='peso',
        ),
    ]
