# Generated by Django 5.2.6 on 2025-10-03 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_creditos_disciplina_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_progressao', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentual_rendimento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('percentual_progressao_intercambio', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('semestre_atual', models.PositiveSmallIntegerField(default=1)),
                ('disciplinas_cursadas', models.PositiveIntegerField(default=0)),
                ('data_calculo', models.DateTimeField(auto_now=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progressao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
