# Generated by Django 5.2.6 on 2025-10-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_progressaoacademica'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
